# This is a config for E2B sandbox template.
# You can use template ID (g3bpy1pqmflzkmm166bi) or template name (logick) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("logick") # Sync sandbox
# sandbox = await AsyncSandbox.create("logick") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('logick')

team_id = "74b1f007-2d0a-4bca-add6-2bbf05632535"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "logick"
template_id = "g3bpy1pqmflzkmm166bi"
